server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://132.232.178.235:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: Lian1998!
  redis:
    database: 0
    host: 132.232.178.235
    port: 6379
    password: lian1998