server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: Lian1998!
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: lian1998
  rabbitmq:
    addresses: 192.168.133.128:5672,192.168.133.129:5672,192.168.133.130:5672
    username: soulblack
    password: lian1998
    virtual-host: / # 连接到rabbitMQ的vhostc
    connection-timeout: 15000
    publisher-returns: true
    listener:
      simple:
        # 消息收到后进行手工签收 默认为auto 自动
        acknowledge-mode: manual
    publisher-confirm-type: correlated
#    NONE值是禁用发布确认模式，是默认值
#    CORRELATED值是发布消息成功到交换器后会触发回调方法，如1示例
#    SIMPLE值经测试有两种效果，其一效果和CORRELATED值一样会触发回调方法，
#  其二在发布消息成功后使用rabbitTemplate调用waitForConfirms或waitForConfirmsOrDie方法等待broker节点返回发送结果，
#  根据返回结果来判定下一步的逻辑，要注意的点是waitForConfirmsOrDie方法如果返回false则会关闭channel，则接下来无法发送消息到broker;


elastic:
  job:
    zk:
      namespace: elastic-job
      serverLists: 192.168.133.128:2181,192.168.133.129:2181,192.168.133.130:2181
